version: '3.9'

services:
  banco:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@banco:5432/${DB_NAME}
    depends_on:
      - banco
    ports:
      - "4000:4000"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres: