    services:
      banco:
        image: postgres:latest
        environment:
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_DB: ${DB_NAME}
        volumes:
          - postgres:/var/lib/postgresql/data
        ports:
          - "6433:5432"
        networks:
          - postgres
        restart: unless-stopped
    
    networks:
      postgres:
        driver: bridge
    
    volumes:
        postgres:

### docker-compose up -d 
### Com comando acima executamos esse arquivo e subimos o banco e o pgadmin